name: Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

env:
  ENVIRONMENT: "production"

jobs:
  performance_regression_testing:
    name: Performance regression testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24.1' # The Go version to download (if necessary) and use.
      - name: Run benchmark
        run: go test -bench=. | tee output.txt
      - name: Analyze benchmark results with Nyrkiö
        uses: nyrkio/change-detection@v2
        with:
          tool: 'go'
          output-file-path: output.txt
          nyrkio-token: ${{ secrets.NYRKIO_JWT_TOKEN }}
